#!/usr/bin/env bash
# ============================================================
# install_hook.sh — Install the post-receive hook into a bare Git repo
# ============================================================
# Usage:
#   bash scripts/install_hook.sh /path/to/bare/repo.git [OPTIONS]
#
# Options:
#   --orchestrator-host HOST   SSH host for orchestrator (default: localhost)
#   --orchestrator-user USER   SSH user (default: current user)
#   --orchestrator-port PORT   SSH port (default: 22)
#   --project-dir DIR          Project dir on orchestrator (default: ~/ai-crm)
#   --ssh-key PATH             Path to SSH private key (optional)
#   --force                    Overwrite existing hook without prompting
#
# Example:
#   bash scripts/install_hook.sh /srv/git/ai-crm.git \
#       --orchestrator-host 172.16.12.50 \
#       --project-dir /home/dev/ai-crm
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SOURCE="${SCRIPT_DIR}/post-receive"

# ── Defaults ──
ORCHESTRATOR_HOST="localhost"
ORCHESTRATOR_USER="$(whoami)"
ORCHESTRATOR_PORT="22"
PROJECT_DIR="\$HOME/ai-crm"
SSH_KEY=""
FORCE=false
BARE_REPO=""

# ── Parse arguments ──
usage() {
    echo "Usage: $0 <bare-repo-path> [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --orchestrator-host HOST   SSH host (default: localhost)"
    echo "  --orchestrator-user USER   SSH user (default: \$(whoami))"
    echo "  --orchestrator-port PORT   SSH port (default: 22)"
    echo "  --project-dir DIR          Project dir on orchestrator"
    echo "  --ssh-key PATH             SSH private key path"
    echo "  --force                    Overwrite existing hook"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

BARE_REPO="$1"
shift

while [ $# -gt 0 ]; do
    case "$1" in
        --orchestrator-host) ORCHESTRATOR_HOST="$2"; shift 2 ;;
        --orchestrator-user) ORCHESTRATOR_USER="$2"; shift 2 ;;
        --orchestrator-port) ORCHESTRATOR_PORT="$2"; shift 2 ;;
        --project-dir)       PROJECT_DIR="$2"; shift 2 ;;
        --ssh-key)           SSH_KEY="$2"; shift 2 ;;
        --force)             FORCE=true; shift ;;
        *)                   echo "Unknown option: $1"; usage ;;
    esac
done

# ── Validate ──
if [ ! -d "${BARE_REPO}" ]; then
    echo "ERROR: Bare repo directory does not exist: ${BARE_REPO}"
    exit 1
fi

if [ ! -d "${BARE_REPO}/hooks" ]; then
    echo "ERROR: ${BARE_REPO}/hooks not found — is this a bare Git repo?"
    exit 1
fi

if [ ! -f "${HOOK_SOURCE}" ]; then
    echo "ERROR: Hook source not found: ${HOOK_SOURCE}"
    exit 1
fi

HOOK_DEST="${BARE_REPO}/hooks/post-receive"

# ── Check existing hook ──
if [ -f "${HOOK_DEST}" ] && [ "${FORCE}" = false ]; then
    echo "WARNING: post-receive hook already exists at ${HOOK_DEST}"
    read -rp "Overwrite? [y/N] " answer
    if [[ ! "${answer}" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# ── Install hook ──
cp "${HOOK_SOURCE}" "${HOOK_DEST}"
chmod +x "${HOOK_DEST}"

# ── Write environment config ──
ENV_FILE="${BARE_REPO}/hooks/post-receive.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by install_hook.sh at $(date)
export ORCHESTRATOR_HOST="${ORCHESTRATOR_HOST}"
export ORCHESTRATOR_USER="${ORCHESTRATOR_USER}"
export ORCHESTRATOR_PORT="${ORCHESTRATOR_PORT}"
export PROJECT_DIR="${PROJECT_DIR}"
export SSH_KEY="${SSH_KEY}"
EOF

# Prepend env sourcing to the hook
TEMP_HOOK="$(mktemp)"
cat > "${TEMP_HOOK}" <<'PREAMBLE'
#!/usr/bin/env bash
# Source environment configuration if available
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "${HOOK_DIR}/post-receive.env" ]; then
    # shellcheck disable=SC1091
    source "${HOOK_DIR}/post-receive.env"
fi
PREAMBLE

# Append original hook content (skip the shebang line)
tail -n +2 "${HOOK_DEST}" >> "${TEMP_HOOK}"
mv "${TEMP_HOOK}" "${HOOK_DEST}"
chmod +x "${HOOK_DEST}"

echo "============================================"
echo "post-receive hook installed successfully!"
echo "  Hook:   ${HOOK_DEST}"
echo "  Config: ${ENV_FILE}"
echo ""
echo "Configuration:"
echo "  Orchestrator: ${ORCHESTRATOR_USER}@${ORCHESTRATOR_HOST}:${ORCHESTRATOR_PORT}"
echo "  Project dir:  ${PROJECT_DIR}"
echo "  SSH key:      ${SSH_KEY:-<default>}"
echo "============================================"
